"""
Django settings for NewsPaper project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qqqs$!ph&dti^$4_1v+91@ws@rpozx%-zt(1tyw^z2t5p1+ii0'


ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'sign',
    'protect',

    'django.contrib.sites',
    'django.contrib.flatpages',
    'django_filters',
    'django_apscheduler',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.cache.FetchFromCacheMiddleware',
    'myapp.mymiddleware.MobileOrFullMiddleware',
]

ROOT_URLCONF = 'NewsPaper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

WSGI_APPLICATION = 'NewsPaper.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache_files'), # Указываем, куда будем сохранять кэшируемые файлы! Не забываем создать папку cache_files внутри папки с manage.py!
    }
}

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SITE_ID = 1

LOGIN_URL = '/accounts/login/'

LOGIN_REDIRECT_URL = '/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'

ACCOUNT_FORMS = {'signup': 'sign.models.BasicSignupForm'}


EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 465 
EMAIL_HOST_USER = 'ViacheslavDan803@gmail.com' 
EMAIL_HOST_PASSWORD = 'kudoakhbdwpaosya' 
EMAIL_USE_SSL = True 

DEFAULT_FROM_EMAIL = '' 

APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
 
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds

ADMINS = [('John', 'DanViacheslav@gmail.com'), ('Mary', 'ViacheslavDan803@gmail.com')]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            'format': '%(asctime)s %(levelname)s %(message)s'
        },
        'warnFormat': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s'
        },
        'errorFormat': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s %(exc_info)s'
        },
        'fileFormat': {
            'format': '%(asctime)s %(levelname)s %(module)s %(message)s'
        },
        'mailFormat': {
            'format': '%(asctime)s %(levelname)s %(message)s %(pathname)s'
        }
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'filters': ['require_debug_true'],
            'formatter': 'verbose'
        },
        'consoleWarn': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'warnFormat'
        },
        'consoleError': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
            'formatter': 'errorFormat'
        },
        'fileGeneral': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filters': ['require_debug_false'],
            'filename': 'myapp/logging/general.log',
            'formatter': 'fileFormat'
        },
        'fileErrors': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'myapp/logging/errors.log',
            'formatter': 'errorFormat'
        },
        'fileSecurity': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': 'myapp/logging/security.log',
            'formatter': 'fileFormat'
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'formatter': 'mailFormat'
        }
    },
    'loggers': {
        'django': {
            'level': 'DEBUG',
            'handlers': ['console', 'consoleWarn', 'consoleError', 'fileGeneral', 'fileErrors', 'fileSecurity'],
            'propagate': True,
        },
        'django.request': {
            'level': 'DEBUG',
            'handlers': ['mail_admins', 'consoleError', 'fileErrors'],
            'propagate': False
        },
        'django.server': {
            'handlers': ['mail_admins', 'fileErrors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.template': {
            'handlers': ['fileErrors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.db_backends': {
            'handlers': ['fileErrors'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['fileSecurity'],
            'level': 'DEBUG',
            'propagate': False,
        },
    }
}